# Netlify Build Configuration

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  base = "me-api-frontend"
  publish = "me-api-frontend/dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
