# Netlify Build Configuration

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  base = "me-api-frontend"
  publish = "me-api-frontend/dist"
  command = "npm run build"
  node_version = "20.19.0"

[build.environment]
  NPM_FLAGS = "--legacy-peer-deps"
